config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'coaches' => 'pages#coaches'
  get 'aboutus' => 'pages#aboutus'
  get 'contactus' => 'pages#contactus'
  get 'signin' => 'pages#signin'
  get 'signup' => 'pages#signup'
  get 'profile' => 'pages#profile'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Matchup</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "Home", root_path %>
    <%= link_to "About Us", aboutus_path %>
    <%= link_to "Contact Us", aboutus_path %>
    <%= link_to "Sign In", signin_path %>
    <%= link_to "Sign Up", signup_path %>
     <%= link_to "Profile", profile_path %>
    <%= yield %>
  </body>
</html>

app/views/pages/aboutus.html.erb
<H1>About Us</H1>

app/views/pages/coaches.html.erb
<H1>Coaches Info</H1>

app/views/pages/contactus.html.erb
<H1>Contact Us</H1>

app/views/pages/home.html.erb
<h1>Welcome to My Site</h1>
<a href ="/coaches">Coaches Profiles</a>

app/views/pages/profile.html.erb
<a href="http://wowslider.com">Click here to visit http://wowslider.com</a>

app/views/pages/signin.html.erb
<H1>Sign In Page</H1>

app/views/pages/signup.html.erb
<H1>Sign Up Page</H1>